# Generated by Django 4.2.5 on 2023-09-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_answer_answer_alter_question_hint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
