# Generated by Django 4.2.5 on 2023-09-21 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_answer_question_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer", old_name="question_text", new_name="question",
        ),
    ]
