# Generated by Django 4.2.5 on 2023-09-23 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_task_counter_customuser_last_login_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_time_spent',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
