# Generated by Django 4.2.5 on 2023-09-22 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_task_remove_question_category_delete_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='theme',
            field=models.IntegerField(choices=[(1, 'Caracteristicas de la onda'), (2, 'Ondas Sonoras'), (3, 'Ondas Armonicas'), (4, 'Ecuacion de la Onda'), (5, 'Energias e info. transferida')], default=1),
        ),
    ]
