# Generated by Django 4.2.5 on 2023-09-24 02:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0004_task_wrongs_counter'),
        ('home', '0005_customuser_total_time_spent'),
    ]
    operations = [
    ]