# Generated by Django 4.2.5 on 2023-09-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_merge_20230923_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='wrongs_counter',
            field=models.IntegerField(default=-1),
        ),
    ]
