# Generated by Django 4.2.5 on 2023-09-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_answer_hint_question_hint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='hint',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
