# Generated by Django 4.2.5 on 2023-09-24 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_parameters_dinamicquestion_dinamicanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinamicanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinamic_question_answer', to='home.dinamicquestion'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinamic_question_parameters', to='home.dinamicquestion'),
        ),
    ]
