# Generated by Django 4.2.5 on 2023-09-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_alter_answer_answer_alter_question_question_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="task", name="counter", field=models.IntegerField(default=0),
        ),
    ]
