# Generated by Django 4.2.5 on 2023-09-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_task_counter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task", name="counter", field=models.IntegerField(default=-1),
        ),
    ]
