# Generated by Django 4.2.5 on 2023-09-25 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_merge_20230924_0148'),
        ('home', '0011_remove_dinamicanswer_result'),
    ]

    operations = [
    ]
