# Generated by Django 4.2.5 on 2023-09-25 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_merge_20230923_2305'),
        ('home', '0012_merge_20230924_2333'),
    ]

    operations = [
    ]
