# Generated by Django 4.2.5 on 2023-09-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_merge_20230925_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dinamicquestion',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium')], default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=1000),
        ),
    ]
