# Generated by Django 4.2.5 on 2023-09-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_answer_answer_alter_dinamicquestion_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinamicquestion',
            name='hint',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='hint',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
