# Generated by Django 4.2.5 on 2023-09-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_customuser_last_task_dinamicanswer_hint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='quest',
            field=models.ManyToManyField(related_name='tasks', to='home.question'),
        ),
    ]
