# Generated by Django 4.2.5 on 2023-09-28 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_question_task_task_quest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='quest',
        ),
        migrations.AddField(
            model_name='question',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_questions', to='home.task'),
        ),
    ]
